### ISSUE TITLE
single yaml where game choice is random creates "error decoding response body" error.

### ISSUE THREAD

**Issue by CaitSith2** [Eijebong/Archipelago-lobby#8]
What I expected was for the possible games to be listed, based on the rolling of the game dictionary.

What I get instead, is error decoding response body, even where there is ONLY one possible game that can be rolled for the given yaml.

Both of these failed with "error decoding response body"
[CaitSith2-Factorio.yaml](https://github.com/user-attachments/files/16243284/CaitSith2-Factorio.txt)
[CaitSith2-Factorio-Zillion.yaml](https://github.com/user-attachments/files/16243301/CaitSith2-Factorio-Zillion.txt)

And both of these upload successfully, but not at the same time, since the name is not unique across the both of them.
[CaitSith2-valid-Factorio.yaml](https://github.com/user-attachments/files/16243320/CaitSith2-valid-Factorio.txt)
[CaitSith2-valid-Zillion.yaml](https://github.com/user-attachments/files/16243321/CaitSith2-valid-Zillion.txt)

**Comment by CaitSith2** [comment]
Equally invalid, is the single file multi-yaml format., where you separate your archipelago games with ---

**Comment by Eijebong** [comment]
Should be fixed by https://github.com/Eijebong/Archipelago-yaml-checker/commit/fc110a1232dd32de10e635bf073892b69dce1e52 thanks for the report :)
